# Generated by Django 3.2.4 on 2021-08-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('retypepassword', models.TextField()),
            ],
        ),
    ]
