# Generated by Django 3.2.4 on 2021-08-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avodhashopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='retypepassword',
            new_name='password2',
        ),
    ]
