# Generated by Django 3.2.4 on 2021-08-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avodhashopapp', '0004_auto_20210817_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='confirm_password',
            new_name='password2',
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
