# Generated by Django 3.2.4 on 2021-08-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avodhashopapp', '0005_auto_20210817_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='shop',
        ),
    ]
