# Generated by Django 3.2.4 on 2021-08-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avodhashopapp', '0006_rename_register_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
