# Generated by Django 3.2.4 on 2021-08-26 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avodhashopapp', '0010_rename_items_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date',
            new_name='date_added',
        ),
    ]
