# Generated by Django 3.2.4 on 2021-09-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avodhashopapp', '0013_rename_password2_shop_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
