# Generated by Django 3.2.4 on 2021-09-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avodhashopapp', '0014_item_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='item',
            name='prodt',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
